### ISSUE TITLE
 HTML et CSS devraient être valides et respecter les standards du W3C

### ISSUE THREAD

**Issue by choutrang** [gti525/e17-gestionnaire-salle-webapp#38]
L’utilisation de CSS est obligatoire. Aussi, le HTML et CSS devraient être valides et respecter
les standards du W3C. Vous pouvez utiliser les plugiciels Validity sous Chrome ou les plugiciels
de Firefox suivants pour valider votre code :
https://addons.mozilla.org/fr/firefox/addon/css-validator/
https://addons.mozilla.org/fr/firefox/addon/html-validator/

**Comment by andyhe886** [comment]
Done
